# Generated by Django 4.1.3 on 2022-11-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='direction',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name="Yo'nalish"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='group',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Guruh'),
        ),
    ]
