# Generated by Django 4.1.3 on 2022-11-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_direction_customuser_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('created_at',), 'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='faculty',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Fakultet'),
        ),
    ]
