# Generated by Django 4.1.3 on 2022-11-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_test', '0002_usertest_usertestresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertest',
            name='is_true',
            field=models.BooleanField(default=False),
        ),
    ]
