# Generated by Django 4.1.3 on 2022-11-09 05:09

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('is_true', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Variantlar',
                'verbose_name_plural': 'Variantlar',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='modules')),
                ('name', models.CharField(max_length=500)),
                ('order', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Modul',
                'verbose_name_plural': 'Modullar',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='themes')),
                ('title', models.CharField(max_length=500)),
                ('order', models.PositiveSmallIntegerField()),
                ('content', ckeditor.fields.RichTextField(verbose_name='Mazmuni')),
            ],
            options={
                'verbose_name': 'Modul',
                'verbose_name_plural': 'Modullar',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('answers', models.ManyToManyField(to='modul.answer')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modul.theme')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Testlar',
            },
        ),
    ]
