# Generated by Django 4.1.3 on 2022-11-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modul', '0002_alter_answer_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
