# Generated by Django 4.1.3 on 2022-11-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='themes')),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='books')),
            ],
            options={
                'verbose_name': 'Kitob',
                'verbose_name_plural': 'Kitoblar',
            },
        ),
        migrations.CreateModel(
            name='InternetResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='themes')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'Internet resurs',
                'verbose_name_plural': 'Internet resurslar',
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=500)),
                ('ans1', models.CharField(max_length=200)),
                ('ans2', models.CharField(max_length=200)),
                ('ans3', models.CharField(blank=True, max_length=200, null=True)),
                ('ans4', models.CharField(blank=True, max_length=200, null=True)),
                ('ans5', models.CharField(blank=True, max_length=200, null=True)),
                ('ans6', models.CharField(blank=True, max_length=200, null=True)),
                ('res1', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('res2', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('res3', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('res4', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('res5', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('res6', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': "So'rovnoma",
                'verbose_name_plural': "So'rovnomalar",
            },
        ),
        migrations.CreateModel(
            name='VideoLessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='themes')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(blank=True, null=True)),
                ('iframe', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Video dars',
                'verbose_name_plural': 'Video darslar',
            },
        ),
    ]
