# Generated by Django 4.1.3 on 2022-11-09 09:00

from django.db import migrations, models
import home.validators


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(max_length=200, verbose_name='Kitob muallifi'),
        ),
        migrations.AlterField(
            model_name='books',
            name='file',
            field=models.FileField(upload_to='books', validators=[home.validators.validate_file_extension], verbose_name='Kitob fayli'),
        ),
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(upload_to='themes', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Kitob nomi'),
        ),
        migrations.AlterField(
            model_name='internetresources',
            name='image',
            field=models.ImageField(upload_to='themes', verbose_name='Resurs rasmi'),
        ),
        migrations.AlterField(
            model_name='internetresources',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='internetresources',
            name='url',
            field=models.URLField(verbose_name='Resurs url manzili'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='ans1',
            field=models.CharField(max_length=200, verbose_name='Variant'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='ans2',
            field=models.CharField(max_length=200, verbose_name='Variant'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='ans3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Variant'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='ans4',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Variant'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='ans5',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Variant'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='ans6',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Variant'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='publish',
            field=models.BooleanField(default=False, verbose_name="So'rovnoma holati"),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='title',
            field=models.CharField(max_length=500, verbose_name="So'rovnoma savoli"),
        ),
        migrations.AlterField(
            model_name='videolessons',
            name='iframe',
            field=models.TextField(blank=True, null=True, verbose_name='YouTube ifareme'),
        ),
        migrations.AlterField(
            model_name='videolessons',
            name='image',
            field=models.ImageField(upload_to='video_lessons', verbose_name='Video dars rasmi'),
        ),
        migrations.AlterField(
            model_name='videolessons',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Sarlavha'),
        ),
    ]
