# Generated by Django 4.1.3 on 2022-11-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_videocategory_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('faculty', models.CharField(max_length=100)),
                ('direction', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
