# Generated by Django 4.1.3 on 2022-11-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_books_author_alter_books_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='res1',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='res2',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='res3',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='res4',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='res5',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='res6',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
