# Generated by Django 4.1.3 on 2022-11-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_incomingmessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Kitob url manzili'),
        ),
    ]
